In [56]:
# Here we are importing all the libraries
from pymnet import *
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Problem 1

In [57]:
#Upload the csv file via pandas
assignment_1_data = pd.read_csv("Assignment_1_Data.csv")
assignment_1_data.head(2)

,Timestamp,Student name,Do you have some background on Data Mining (CIS 4523/5523) or Machine Learning,Do you have some background on Python or R programming,Do you have some background on Graphs or Statistics
0,2023/01/19 5:01:18 PM EST,Student 0,Yes,Yes,Yes
1,2023/01/19 5:03:51 PM EST,Student 1,Yes,Yes,Yes

In [58]:
#Get an overview of the data
assignment_1_data.describe()

,Timestamp,Student name,Do you have some background on Data Mining (CIS 4523/5523) or Machine Learning,Do you have some background on Python or R programming,Do you have some background on Graphs or Statistics
count,12,12,12,12,12
unique,12,12,2,1,1
top,2023/01/19 5:01:18 PM EST,Student 0,Yes,Yes,Yes
freq,1,1,9,12,12

In [59]:
#lets drop the unnecessary colums , keep the course column
assignment_1_data_clean = assignment_1_data.drop(['Timestamp', 'Student name'], axis=1)
assignment_1_data_clean.head(2)

,Do you have some background on Data Mining (CIS 4523/5523) or Machine Learning,Do you have some background on Python or R programming,Do you have some background on Graphs or Statistics
0,Yes,Yes,Yes
1,Yes,Yes,Yes

In [60]:
#column header name , we may need to use them in future
column_headers = list(assignment_1_data_clean)
column_headers

['Do you have some background on Data Mining (CIS 4523/5523) or Machine Learning',
 'Do you have some background on Python or R programming',
 'Do you have some background on Graphs or Statistics']

In [61]:
#Convert the values into dummy values so it will be easier
dummies = pd.get_dummies(assignment_1_data_clean)

dummies_clean = dummies.iloc[: , 1:]
dummies_clean_old =dummies_clean
dummies_clean

,Do you have some background on Data Mining (CIS 4523/5523) or Machine Learning_Yes,Do you have some background on Python or R programming_Yes,Do you have some background on Graphs or Statistics_Yes
0,1,1,1
1,1,1,1
2,0,1,1
3,0,1,1
4,1,1,1
5,1,1,1
6,1,1,1
7,1,1,1
8,0,1,1
9,1,1,1
10,1,1,1
11,1,1,1

In [62]:
#convert the pandas data frame into numpy, numpy is easier to access
dummies_clean = dummies_clean.to_numpy()
dummies_clean

array([[1, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [63]:
#let write the metadata on the text file
row, col = dummies_clean.shape
with open('problem1.dat.tex', 'w') as f:
    sentence = "DL" + "\n" + "N=" + str(row) +" " + "NM=" + str(col) + "\n" + "FORMAT = FULLMATRIX DIAGONAL PRESENT" +"\n" +"LEVEL LABELS:"   
    f.write(sentence)
    for l in range(0, col):
        f.write('\n')
        f.write('L'+ str(l))
    f.write("\n")
    f.write("Data =")
    f.write("\n")

In [64]:
#Final Adjacency list and append it to the text file

for k in range(0, col):
    adjacency_matrix_DM_LM = np.zeros((row, row))
    for i in range(0, row):
        for j in range(i,row):
            #print(dummies_clean[i][k],dummies_clean[j][k])
            if dummies_clean[i][k] == dummies_clean[j][k] and i !=j:
                adjacency_matrix_DM_LM[i][j] = 1
                adjacency_matrix_DM_LM[j][i] = 1

    #         else:
    #             print("NO")
    print(adjacency_matrix_DM_LM)
    with open('problem1.dat.tex', 'a') as f:
        data = str(adjacency_matrix_DM_LM)
        data = data.replace("[", "")
        data = data.replace("]", "")
        f.write(data)
        f.write('\n')

[[0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1.]
 [1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0.]]
[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]
[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]

In [65]:
net=read_ucinet("problem1.dat.tex",couplings="none")
net=transforms.threshold(net,1)
fig=draw(net,
             show=True,
             layout="spring",
             layerColorRule={},
             defaultLayerColor="gray",
             nodeLabelRule={},
             edgeColorRule={"rule":"edgeweight","colormap":"jet","scaleby":0.1}
             )

/Users/rahadarmannabid/Documents/Social Network HW/Multilayer-networks-library/pymnet/visuals/drawbackends/mpl.py:74: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

In [66]:
fig.savefig("problem1.pdf")

# Problem 2

In [67]:
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

In [68]:

#rowwise sum
dummies_clean_old['total']=dummies_clean_old.loc[:,:].sum(axis=1)
dummies_value_subject_count = dummies_clean_old.iloc[: , 3:]
dummies_value_subject_count

    total
0       3
1       3
2       2
3       2
4       3
5       3
6       3
7       3
8       2
9       3
10      3
11      3

In [69]:
dummies_value_subject_count = dummies_value_subject_count.to_numpy()
dummies_value_subject_count

array([[3],
       [3],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3]])

In [72]:
k = 0
adjacency_matrix_DM_LM = np.zeros((row, row))
for i in range(0, row):
    for j in range(i,row):
         if dummies_value_subject_count[i][k] == dummies_value_subject_count[j][k] and i !=j:
                adjacency_matrix_DM_LM[i][j] = dummies_value_subject_count[i][k]
                adjacency_matrix_DM_LM[j][i] = dummies_value_subject_count[i][k]

#         else:
#             print("NO")
weited_adjacency_matrix = adjacency_matrix_DM_LM.tolist()
weited_adjacency_matrix

[[0.0, 3.0, 0.0, 0.0, 3.0, 3.0, 3.0, 3.0, 0.0, 3.0, 3.0, 3.0],
 [3.0, 0.0, 0.0, 0.0, 3.0, 3.0, 3.0, 3.0, 0.0, 3.0, 3.0, 3.0],
 [0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0],
 [3.0, 3.0, 0.0, 0.0, 0.0, 3.0, 3.0, 3.0, 0.0, 3.0, 3.0, 3.0],
 [3.0, 3.0, 0.0, 0.0, 3.0, 0.0, 3.0, 3.0, 0.0, 3.0, 3.0, 3.0],
 [3.0, 3.0, 0.0, 0.0, 3.0, 3.0, 0.0, 3.0, 0.0, 3.0, 3.0, 3.0],
 [3.0, 3.0, 0.0, 0.0, 3.0, 3.0, 3.0, 0.0, 0.0, 3.0, 3.0, 3.0],
 [0.0, 0.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [3.0, 3.0, 0.0, 0.0, 3.0, 3.0, 3.0, 3.0, 0.0, 0.0, 3.0, 3.0],
 [3.0, 3.0, 0.0, 0.0, 3.0, 3.0, 3.0, 3.0, 0.0, 3.0, 0.0, 3.0],
 [3.0, 3.0, 0.0, 0.0, 3.0, 3.0, 3.0, 3.0, 0.0, 3.0, 3.0, 0.0]]

In [71]:
G = nx.from_numpy_matrix(np.matrix(weited_adjacency_matrix), create_using=nx.DiGraph)
layout = nx.spring_layout(G)
nx.draw(G, layout)
#nx.draw_networkx_edge_labels(G, pos=layout)
plt.show()

/var/folders/7v/n5x204z51gzf5xzqxv_wglqw0000gn/T/ipykernel_33773/2876050946.py:5: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

#let write the metadata on the text file
row, col = dummies_value_subject_count.shape
with open('problem2.dat.tex', 'w') as f:
    sentence = "DL" + "\n" + "N=" + str(row) +" " + "NM=" + str(col) + "\n" + "FORMAT = FULLMATRIX DIAGONAL PRESENT" +"\n" +"LEVEL LABELS:"   
    f.write(sentence)
    for l in range(0, col):
        f.write('\n')
        f.write('L'+ str(l))
    f.write("\n")
    f.write("Data =")
    f.write("\n")

with open('problem2.dat.tex', 'a') as f:
    data = str(adjacency_matrix_DM_LM)
    data = data.replace("[", "")
    data = data.replace("]", "")
    f.write(data)
    f.write('\n')

net=read_ucinet("problem2.dat.tex",couplings="none")
net=transforms.threshold(net,1)
fig=draw(net,
             show=True,
             layout="spring",
             layerColorRule={},
             defaultLayerColor="gray",
             nodeLabelRule={},
             edgeColorRule={"rule":"edgeweight","colormap":"jet","scaleby":0.1}
             )
fig.savefig("problem2.pdf")

In [ ]:
!echo "# Network-Science-Assignment-1" >> README.md
!git init
!git add .
!git commit -m "first commit"
!git branch -M main
!git remote add origin https://github.com/rahadarmannabid/Network-Science-Assignment-1.git
!git push -u origin main

Reinitialized existing Git repository in /Users/rahadarmannabid/Documents/Social Network HW/Multilayer-networks-library/.git/
[master dd96100] first commit
 Committer: Rahad Arman Nabid <rahadarmannabid@Rahads-MacBook-Air.local>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 77 files changed, 3566 insertions(+), 1 deletion(-)
 create mode 100644 .DS_Store
 create mode 100644 .ipynb_checkpoints/Home Work Problem 1, 2-checkpoint.ipynb
 create mode 100644 .ipynb_checkpoints/Problem 3-checkpoint.ipynb
 create mode 100644 .ipynb_checkpoints/Problem 4-checkpoint.ipynb
 create mode 100644 Assignment_1_Data.csv
 create mode 100644 Assignment_1_supplement_2_Example data file for pymnet.dat
 create mode 100644 Home Work 1.py
 create mode 100644 Home Work Problem 1, 2.ipynb
 create mode 100644 Problem 3.ipynb
 create mode 100644 Problem 3.py
 create mode 100644 Problem 4.ipynb
 create mode 100644 net.pdf
 create mode 100644 problem1.dat.tex
 create mode 100644 problem1.pdf
 create mode 100644 problem2.dat.tex
 create mode 100644 problem2.png
 create mode 100644 problem_4_distribution_part_1.zip
 create mode 100644 problem_4_part_1.png
 create mode 100644 pymnet/__pycache__/__init__.cpython-311.pyc
 create mode 100644 pymnet/__pycache__/__init__.cpython-39.pyc
 create mode 100644 pymnet/__pycache__/cc.cpython-311.pyc
 create mode 100644 pymnet/__pycache__/cc.cpython-39.pyc
 create mode 100644 pymnet/__pycache__/diagnostics.cpython-311.pyc
 create mode 100644 pymnet/__pycache__/diagnostics.cpython-39.pyc
 create mode 100644 pymnet/__pycache__/models.cpython-311.pyc
 create mode 100644 pymnet/__pycache__/models.cpython-39.pyc
 create mode 100644 pymnet/__pycache__/net.cpython-311.pyc
 create mode 100644 pymnet/__pycache__/net.cpython-39.pyc
 create mode 100644 pymnet/__pycache__/netio.cpython-311.pyc
 create mode 100644 pymnet/__pycache__/netio.cpython-39.pyc
 create mode 100644 pymnet/__pycache__/nxwrap.cpython-311.pyc
 create mode 100644 pymnet/__pycache__/nxwrap.cpython-39.pyc
 create mode 100644 pymnet/__pycache__/transforms.cpython-311.pyc
 create mode 100644 pymnet/__pycache__/transforms.cpython-39.pyc
 create mode 100644 pymnet/graphlets/__pycache__/__init__.cpython-311.pyc
 create mode 100644 pymnet/graphlets/__pycache__/__init__.cpython-39.pyc
 create mode 100644 pymnet/graphlets/__pycache__/graphlet_measures.cpython-311.pyc
 create mode 100644 pymnet/graphlets/__pycache__/graphlet_measures.cpython-39.pyc
 create mode 100644 pymnet/graphlets/__pycache__/graphlets.cpython-311.pyc
 create mode 100644 pymnet/graphlets/__pycache__/graphlets.cpython-39.pyc
 create mode 100644 pymnet/graphlets/__pycache__/independent_equations.cpython-311.pyc
 create mode 100644 pymnet/graphlets/__pycache__/independent_equations.cpython-39.pyc
 create mode 100644 pymnet/isomorphisms/__pycache__/__init__.cpython-311.pyc
 create mode 100644 pymnet/isomorphisms/__pycache__/__init__.cpython-39.pyc
 create mode 100644 pymnet/isomorphisms/__pycache__/blissbackend.cpython-311.pyc
 create mode 100644 pymnet/isomorphisms/__pycache__/blissbackend.cpython-39.pyc
 create mode 100644 pymnet/isomorphisms/__pycache__/isomcore.cpython-39.pyc
 create mode 100644 pymnet/isomorphisms/__pycache__/nxbackend.cpython-311.pyc
 create mode 100644 pymnet/isomorphisms/__pycache__/nxbackend.cpython-39.pyc
 create mode 100644 pymnet/sampling/__pycache__/__init__.cpython-39.pyc
 create mode 100644 pymnet/sampling/__pycache__/creators.cpython-39.pyc
 create mode 100644 pymnet/sampling/__pycache__/dumb.cpython-39.pyc
 create mode 100644 pymnet/sampling/__pycache__/esu.cpython-39.pyc
 create mode 100644 pymnet/sampling/__pycache__/reqs.cpython-39.pyc
 create mode 100644 pymnet/visuals/__pycache__/__init__.cpython-311.pyc
 create mode 100644 pymnet/visuals/__pycache__/__init__.cpython-39.pyc
 create mode 100644 pymnet/visuals/__pycache__/drawassigners.cpython-311.pyc
 create mode 100644 pymnet/visuals/__pycache__/drawassigners.cpython-39.pyc
 create mode 100644 pymnet/visuals/__pycache__/drawcore.cpython-311.pyc
 create mode 100644 pymnet/visuals/__pycache__/drawcore.cpython-39.pyc
 create mode 100644 pymnet/visuals/__pycache__/drawnet.cpython-311.pyc
 create mode 100644 pymnet/visuals/__pycache__/drawnet.cpython-39.pyc
 create mode 100644 pymnet/visuals/__pycache__/layouts.cpython-311.pyc
 create mode 100644 pymnet/visuals/__pycache__/layouts.cpython-39.pyc
 create mode 100644 pymnet/visuals/__pycache__/webplots.cpython-311.pyc
 create mode 100644 pymnet/visuals/__pycache__/webplots.cpython-39.pyc
 create mode 100644 pymnet/visuals/drawbackends/__pycache__/__init__.cpython-311.pyc
 create mode 100644 pymnet/visuals/drawbackends/__pycache__/__init__.cpython-39.pyc
 create mode 100644 pymnet/visuals/drawbackends/__pycache__/mpl.cpython-311.pyc
 create mode 100644 pymnet/visuals/drawbackends/__pycache__/mpl.cpython-39.pyc
 create mode 100644 pymnet/visuals/drawbackends/__pycache__/threejs.cpython-311.pyc
 create mode 100644 pymnet/visuals/drawbackends/__pycache__/threejs.cpython-39.pyc
 create mode 100644 readme.dat
 create mode 100644 readme.dat.tex
 create mode 100644 test.dat.txt
 create mode 100644 testnet.pdf
error: remote origin already exists.
Username for 'https://github.com':

In [ ]:
!rahadarmannabid